"""
Integration test fixtures — generated by AI Factory.
Tests send real HTTP requests to BASE_URL (no in-process app import required).
Override the target URL via the TEST_BASE_URL environment variable.
"""
from __future__ import annotations

import os

import pytest_asyncio
from httpx import AsyncClient

BASE_URL = os.environ.get("TEST_BASE_URL", "https://lms-core-api-production.up.railway.app")


@pytest_asyncio.fixture
async def client() -> AsyncClient:
    async with AsyncClient(base_url=BASE_URL, follow_redirects=True, timeout=30.0) as c:
        yield c


@pytest_asyncio.fixture
async def auth_headers(client: AsyncClient) -> dict[str, str]:
    """Obtain authentication headers for protected endpoints.

    Tries common REST authentication patterns in order and returns Bearer
    headers on the first success.  Falls back to a recognisably invalid
    token so unauthorised-endpoint tests still receive a 401/403.
    """
    for path, payload in [
        ("/auth/sign-in", {"email": "admin@test.com", "password": "Password123!"}),
        ("/auth/login", {"username": "admin", "password": "Password123!"}),
        ("/login", {"username": "admin", "password": "Password123!"}),
    ]:
        try:
            resp = await client.post(path, json=payload)
            if resp.status_code == 200:
                data = resp.json()
                token = data.get("access_token") or data.get("token", "")
                if token:
                    return {"Authorization": f"Bearer {token}"}
        except Exception:  # noqa: BLE001
            pass
    return {"Authorization": "Bearer __invalid_smoke_token__"}
